正确报错

diff --git a/src/usr/bin/apm b/src/usr/bin/apm
--- a/src/usr/bin/apm
+++ b/src/usr/bin/apm
@@ -111,6 +111,13 @@ case "$1" in
     command=$1
     shift
     amber-pm-debug aptss "$command" "$@"
+        exit_code=$?
+    if [ $exit_code -eq 0 ]; then
+        log.info "Operation successful"
+    else
+        log.error "Error: Operation failed"
+        exit $exit_code
+    fi
     amber-pm-debug amber-pm-dstore-patch
     apm-nvidia-toggle
     ;;
